name: "Check Template"
description: "Automatically close issues that don't follow any defined templates."
author: "machiecodes"

branding:
  icon: "archive"
  color: "white"

inputs:
  close-message:
    description: The message to post when closing an issue.
    required: false
    default: "### This issue is being automatically closed.\nPlease reopen your issue following one of the templates."
  close-label:
    description: The label to apply when closing an issue.
    required: false

runs:
  using: "node24"
  main: "dist/index.js"