name: Check Template

on:
  issues:
    types: [ opened ]

jobs:
  issue-moderator:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Check Template
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          close-message: "This issue has been closed, sorry!"
          close-label: "invalid"